[project]
name = "rust-coreutils"
version = "0.0.1"
authors = ["don <don@0xbeef.org>"]

[dependencies]
getopts = "0.2.10"

[[bin]]
name = "echo"
path = "src/echo/echo.rs"

[[bin]]
name = "false"
path = "src/false/false.rs"

[[bin]]
name = "true"
path = "src/true/true.rs"
